### ISSUE TITLE
翻訳エラー: Enable EU compliance for Adobe Analytics で EU

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/experience-platform.ja-JP#1]
Issue in ./help/tags/extensions/client/analytics/overview.md

[現在の翻訳] Enable EU compliance for Adobe Analytics で EU
[期待される翻訳] Adobe AnalyticsのEUコンプライアンスを有効にする
[英文] Enable EU compliance for Adobe Analytics

**Comment by mak-adobe** [comment]
@khagiwar ありがとうございます。G11N-13002のチケットで調査を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。ご協力ありがとうございました。
