### ISSUE TITLE
記述子の制限の誤訳（24/8/24の原文更新の未反映）

### ISSUE THREAD

**Issue by notakemu** [AdobeDocs/experience-platform.ja-JP#2]
Issue in ./help/xdm/api/descriptors.md

[Source] The maximum number of descriptors that can be applied to an organization’s sandbox is 4000.
[Current translation] スキーマに適用できる記述子の最大数は 4000 です。
[Expected translation] 組織のサンドボックスに適用できる記述子の最大数は 4000 です。

**Comment by notakemu** [comment]
https://github.com/AdobeDocs/experience-platform.en/commit/866e00459c66ea4678cd98d119a7451fd8e78253

**Comment by mak-adobe** [comment]
@notakemu ありがとうございます。 G11N-17598 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@notakemu 修正が完了しました。ご協力ありがとうございました。

**Comment by notakemu** [comment]
@mak-adobe ご対応ありがとうございました！
